// Categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
// Posts
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const DETELE_POST = 'DETELE_POST';
export const ADDED_POST = 'ADDED_POST';
export const UPDATED_POST = 'UPDATED_POST';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
// Comments
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const ADDED_COMMENT = 'ADDED_COMMENT';
export const UPDATED_COMMENT = 'UPDATED_COMMENT';
export const DETELE_COMMENT = 'DETELE_COMMENT';
